kubernetes-sigs/minibroker

- charts/minibroker/templates/deployment.yaml
- cmd/minibroker/main.go
- pkg/broker/broker.go
- pkg/broker/options.go
- pkg/helm/helm.go
We would like to use a staging registry for services that we're working on rather than the official charts repo.
This PR adds a command line option to the broker that's configured during a helm install of the broker itself.
> Add option for a configurable Helm repo

- pkg/minibroker/minibroker.go
- pkg/minibroker/minibroker_test.go
CF apps [look for service tags](https://github.com/pivotal-cf/cf-redis-example-app/blob/4041cc349fc1535385d12b68264e70de5f49a347/lib/app.rb#L73) to use services. Helm charts [provide keywords](https://github.com/kubernetes/charts/blob/fd35ab34bfd26878fb5970fbc7c3e75760df10ec/stable/redis/Chart.yaml#L6) that can be used as these tags.
This PR adds the tags to the [Service object](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#service-object) in the OSB API.
This saves a step in app deployment in CF. Currently a deployment looks like this:
```
cd cf-example-redis-app
cf push --no-start
cf set-env redis-example-app service_name r
cf bind-service redis-example-app r
cf start redis-example-app
```
By using tags, we can skip the `set-env` step.
Unfortunately the helm …
> Get helm chart's keywords to use as broker tags

- Makefile
- build/publish-images.sh
- charts/minibroker/values.yaml
Publish the minibroker image to quay because there is better security
there. After the docker security breach it became clear that using my
own personal login for our CI wasn't acceptable, and quay lets me make
robot accounts easily.
This also sets us up to migrate the repository to kubernetes-sigs where
they publish to quay anyway.
> Switch to quay.io

- CONTRIBUTING.md
- OWNERS
- SECURITY_CONTACTS
- code-of-conduct.md
Add the template files necessary to move this repository to kubernetes-sigs. These were copied from https://github.com/kubernetes/kubernetes-template-project and tweaked a bit to show how to build and test minibroker.
> Add k8s template files

- README.md
Service Catalog CLI (svcat) was set to old kubernetes incubator repo. Adjusted to new site for documentation.
Issue #23
> Adjusted README.md link for svcat cli

- Gopkg.lock
- Gopkg.toml
- pkg/broker/broker.go
- pkg/minibroker/minibroker.go
- vendor/github.com/pmorie/osb-broker-lib/pkg/broker/interface.go
- vendor/github.com/pmorie/osb-broker-lib/pkg/broker/types.go
- vendor/github.com/pmorie/osb-broker-lib/pkg/rest/apisurface.go
- vendor/github.com/pmorie/osb-broker-lib/pkg/server/server.go
This implements async binding (and matching cleanup in async unbinding).
Since we do no work in unbinding anyway, it is always synchronous.
Note that this requires bumping osb-broker-lib to a version that supports async bind.
> Implement async bind

- pkg/tiller/tiller.go
A naive attempt to be more consistent on waiting for the underlying resource Helm creates.
> fix: wait for chart to be ready

- .travis.yml
- Makefile
- charts/minibroker/templates/rbac.yaml
- charts/minibroker/values.yaml
- ci/test_integration.sh
- hack/create-cluster.sh
Improving the RBAC so that Minibroker doesn't operate as cluster-admin. Also, the new API for RBAC allows disabling it completely or making it namespaced so that Minibroker will only be allowed to manage whitelisted namespaces.
> fix: no cluster admin

- ci/test_integration.sh
Other PRs started to fail on this timeout. Since this depends on various external network accesses, it seems prudent to bump the value to a way larger one.
> fix: bump Travis timeout

- charts/minibroker/templates/_helpers.tpl
- charts/minibroker/templates/broker.yaml
- charts/minibroker/templates/deployment.yaml
- charts/minibroker/templates/rbac.yaml
- charts/minibroker/templates/service.yaml
Cherry-picked the commit from https://github.com/SUSE/minibroker/pull/19, then applied some fixes to allow other labels to be set without having to set them in the template.
> refactor: shared labels template

- README.md
- charts/minibroker/templates/broker.yaml
- pkg/minibroker/provider.go
The cluster domain can be different than `cluster.local`.
Fixes https://github.com/kubernetes-sigs/minibroker/issues/45.
> fix: remove hardcoded cluster domains

- build/image.sh
- charts/minibroker/templates/deployment.yaml
- docker/Dockerfile
- docker/rootfs/etc/passwd
Note: The docker image artifacts had to be moved from image/ to docker/
because the "image" name is somehow special to "docker build", ADD
commands were not working from there.
Fixes #39
> fix: Do not run as root, use read-only filesystem

- ci/test_integration.sh
It's reasonable to assume the CI can sometimes degrade the performance and take longer to complete the integration tests.
> bump: integration tests timeout on CI

- charts/wordpress/templates/deployment.yaml
- charts/wordpress/templates/mysql-instance.yaml
- charts/wordpress/values.yaml
New versions of Kubernetes does not supports `extensions/v1beta1`:
```
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"
```
> update wordpress deployment

- README.md
- pkg/minibroker/minibroker.go
- pkg/minibroker/rabbitmq.go
- tests/integration/minibroker_test.go
- tests/integration/resources/rabbitmq_client.tmpl.yaml
This pr adds support for deploying rabbitmq.
It also fixes the problem of namespaces becoming undeletable if a chart was already deleted but minibroker still thinks it needs to clean up. I encountered a lot when running the integration tests.
> feat: Add support for deploying rabbitmq

- .travis.yml
The current conditions are not doing exactly what we intend. It misses a top-level condition to also trigger the tags.
Tested with [travis-conditions](https://github.com/travis-ci/travis-conditions):
- `{"tag": "", "branch": "master", "repo": "kubernetes-sigs/minibroker"}` - should validate.
- `{"tag": "v1.0.0-rc1", "branch": "v1.0.0-rc1", "repo": "kubernetes-sigs/minibroker"}` - should validate.
- `{"tag": "", "branch": "v1.0.0-rc1", "repo": "kubernetes-sigs/minibroker"}` - should invalidate.
> fix: CI conditions

- pkg/minibroker/mariadb.go
- pkg/minibroker/mongodb.go
- pkg/minibroker/mysql.go
- pkg/minibroker/postgres.go
- pkg/minibroker/redis.go
The protocol names are constants and should never rely on the name of the service port.
> fix: protocol names on bind credentials

- pkg/broker/broker.go
- pkg/broker/broker_test.go
- pkg/broker/mocks/mock_broker.go
- pkg/minibroker/mariadb.go
- pkg/minibroker/minibroker.go
- pkg/minibroker/minibroker_test.go
- pkg/minibroker/mongodb.go
- pkg/minibroker/mysql.go
- pkg/minibroker/postgres.go
- pkg/minibroker/provider.go
- pkg/minibroker/provider_test.go
- pkg/minibroker/rabbitmq.go
- pkg/minibroker/redis.go
This refactor improves the `Provider.Bind` logic by being clearer on what parameters are used for finding the expected keys and by introducing new types wrapping `map[string]interface{}` for dealing with repetitive actions.
> refactor: improve Provider logic

- charts/minibroker/templates/deployment.yaml
Since we have a read-only root filesystem, we missed the cache volume. In some systems, it will be enforced and make Minibroker fail to download the repository index.
> fix: missing cache volume

- Makefile
This PR bumps to the latest patch version of Go for the builder image.
For more details: https://golang.org/doc/devel/release.html#go1.14.minor.
```
go1.14.8 (released 2020/09/01) includes security fixes to the net/http/cgi and net/http/fcgi packages. See the Go 1.14.8 milestone on our issue tracker for details.
go1.14.9 (released 2020/09/09) includes fixes to the compiler, linker, runtime, documentation, and the net/http and testing packages. See the Go 1.14.9 milestone on our issue tracker for details.
```
> bump: Go builder image

- build/image.sh
`docker buildx` speeds the image build considerably. This PR adds an option to use it. It's not the default behaviour as it's still an experimental docker feature and not part of the stable release. It's useful for quicker development iteration.
> feat: add optional docker buildx
